[package]
name = "mineral-config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow         = "1.0"
config_rs      = { package = "config", version = "0.15" }
once_cell      = "1.21"
serde          = { version = "1.0", features   = ["derive"] }
tracing        = "0.1"
derive-getters = "0.5"
mineral-platform = { path = "../mineral-platform" }
