[package]
name = "mineral-log"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow             = { workspace = true }
tracing-appender   = { workspace = true }
tracing-subscriber = { workspace = true }

mineral-platform = { workspace = true }
